const collegesData = [
  {
    id: 1,
    name: "IIT Madras - Indian Institute of Technology (IITM), Chennai",
    location: "Chennai, Tamil Nadu",
    fees: 209550,
    placement: "21,40,000",
    userReview: 8.4,
    ranking: "#1 in India 2023",
    featured: true,
    course: "B.Tech Computer Science Engineering",
    cutoff: "JEE-Advanced 2022 Cutoff: 164",
    applyLink: "https://www.iitm.ac.in/apply",
    brochureLink: "https://www.iitm.ac.in/download-brochure",
  },
  {
    id: 2,
    name: "IIT Delhi - Indian Institute of Technology (IITD), New Delhi",
    location: "New Delhi, Delhi",
    fees: 256450,
    placement: "25,20,000",
    userReview: 8.7,
    ranking: "#2 in India 2023",
    featured: false,
    course: "B.Tech Electrical Engineering",
    cutoff: "JEE-Advanced 2022 Cutoff: 150",
    applyLink: "https://www.iitd.ac.in/apply",
    brochureLink: "https://www.iitd.ac.in/download-brochure",
  },
  {
    id: 3,
    name: "Parul University, Vadodara",
    location: "Vadodara, Gujarat",
    fees: 149000,
    placement: "4,00,000",
    userReview: 8.1,
    ranking: "#147 in India 2023",
    featured: false,
    course: "B.Tech Mechanical Engineering",
    cutoff: "GUJCET 2022 Cutoff: 340",
    applyLink: "https://www.paruluniversity.ac.in/apply",
    brochureLink: "https://www.paruluniversity.ac.in/download-brochure",
  },
  {
    id: 4,
    name: "IIT Bombay - Indian Institute of Technology (IITB), Mumbai",
    location: "Mumbai, Maharashtra",
    fees: 229300,
    placement: "21,32,000",
    userReview: 8.8,
    ranking: "#3 in India 2023",
    featured: true,
    course: "B.Tech Civil Engineering",
    cutoff: "JEE-Advanced 2022 Cutoff: 180",
    applyLink: "https://www.iitb.ac.in/apply",
    brochureLink: "https://www.iitb.ac.in/download-brochure",
  },
  {
    id: 5,
    name: "IIT Kanpur - Indian Institute of Technology (IITK), Kanpur",
    location: "Kanpur, Uttar Pradesh",
    fees: 213400,
    placement: "20,00,000",
    userReview: 8.6,
    ranking: "#4 in India 2023",
    featured: false,
    course: "B.Tech Aerospace Engineering",
    cutoff: "JEE-Advanced 2022 Cutoff: 170",
    applyLink: "https://www.iitk.ac.in/apply",
    brochureLink: "https://www.iitk.ac.in/download-brochure",
  },
  {
    id: 6,
    name: "BITS Pilani - Birla Institute of Technology and Science, Pilani",
    location: "Pilani, Rajasthan",
    fees: 190000,
    placement: "18,50,000",
    userReview: 8.3,
    ranking: "#5 in India 2023",
    featured: true,
    course: "B.E. Computer Science",
    cutoff: "BITSAT 2022 Cutoff: 300",
    applyLink: "https://www.bits-pilani.ac.in/apply",
    brochureLink: "https://www.bits-pilani.ac.in/download-brochure",
  },
  {
    id: 7,
    name: "IIT Kharagpur - Indian Institute of Technology (IITKGP), Kharagpur",
    location: "Kharagpur, West Bengal",
    fees: 222000,
    placement: "23,00,000",
    userReview: 8.5,
    ranking: "#6 in India 2023",
    featured: false,
    course: "B.Tech Chemical Engineering",
    cutoff: "JEE-Advanced 2022 Cutoff: 160",
    applyLink: "https://www.iitkgp.ac.in/apply",
    brochureLink: "https://www.iitkgp.ac.in/download-brochure",
  },
  {
    id: 8,
    name: "IIT Roorkee - Indian Institute of Technology (IITR), Roorkee",
    location: "Roorkee, Uttarakhand",
    fees: 215000,
    placement: "19,50,000",
    userReview: 8.2,
    ranking: "#7 in India 2023",
    featured: false,
    course: "B.Tech Biotechnology",
    cutoff: "JEE-Advanced 2022 Cutoff: 155",
    applyLink: "https://www.iitr.ac.in/apply",
    brochureLink: "https://www.iitr.ac.in/download-brochure",
  },
  {
    id: 9,
    name: "IIT Guwahati - Indian Institute of Technology (IITG), Guwahati",
    location: "Guwahati, Assam",
    fees: 210000,
    placement: "22,00,000",
    userReview: 8.4,
    ranking: "#8 in India 2023",
    featured: true,
    course: "B.Tech Electronics and Communication Engineering",
    cutoff: "JEE-Advanced 2022 Cutoff: 165",
    applyLink: "https://www.iitg.ac.in/apply",
    brochureLink: "https://www.iitg.ac.in/download-brochure",
  },
  {
    id: 10,
    name: "VIT University, Vellore",
    location: "Vellore, Tamil Nadu",
    fees: 175000,
    placement: "12,00,000",
    userReview: 7.9,
    ranking: "#9 in India 2023",
    featured: false,
    course: "B.Tech Information Technology",
    cutoff: "VITEEE 2022 Cutoff: 45000",
    applyLink: "https://www.vit.ac.in/apply",
    brochureLink: "https://www.vit.ac.in/download-brochure",
  },
];

export default collegesData;
